# Config file for PizzaGo
# Each value must be an integer strictly positive

times: # Times to perform each step in miliseconds
  process: 1
  prepare: 2
  bake: 5
  qualityCheck: 1
parameters: 
  NumberOfWorkers: 2   # Number of workers in the pizzeria
  NumberOfOvens: 2     # Number of Ovens in the pizzeria
  NumberOfOrders: 500  # Number of Orders to take
